from remotecontrol import *

channel = [[6, "SBS"], [7, "KBS2"], [9, "KBS1"], [11, "MBC"]]

if __name__ == "__main__":
    rc = RemoteControl()
    rc.powerOnRemoteControl(channel)
    print(rc.getenable())
    print(rc.currentchannel)
    print(rc.gotoChannel(20))
    print(rc.gotoChannel(11))
    print(rc.nextChannel())
    print(rc.previousChannel())
    print()
    print(rc.currentchannel)
    print(rc.blockChannel())
    print(rc.unblockChannel(20))
    print(rc.unblockChannel(11))
    rc.favorChannel()
    rc.favorChannel()
    rc.favorChannel()
    rc.favorChannel()
    rc.nextChannel()
    rc.favorChannel()
    rc.nextChannel()
    rc.favorChannel()
    rc.favorChannel()
    rc.nextChannel()
    rc.favorChannel()
    rc.favorChannel()
    rc.favorChannel()
    print(rc.aiNextChannel())
    print(rc.aiNextChannel())
    print(rc.aiNextChannel())
    print(rc.aiPreviousChannel())
    print(rc.aiPreviousChannel())
    print(rc.aiPreviousChannel())
